### ISSUE TITLE
Text Error

### ISSUE THREAD

**Issue by user706** [commschamp/cc.demo1.commsdsl#2]
Hi,

Description error in this line: [link](https://github.com/arobenko/cc.demo1.commsdsl/blob/dd4e1dc1fc150fc02c50972a7c7b744a4f424ce5/dsl/schema.xml#L177)

**Comment by user706** [comment]
Also: Better if name [here](https://github.com/arobenko/cc.demo1.commsdsl/blob/dd4e1dc1fc150fc02c50972a7c7b744a4f424ce5/dsl/schema.xml#L248), is `CountPrefix`

**Comment by user706** [comment]
This is optional right? [link](https://github.com/arobenko/cc.demo1.commsdsl/blob/dd4e1dc1fc150fc02c50972a7c7b744a4f424ce5/dsl/schema.xml#L251)

The element-bundle has fixed size anyway, so we're forcing a prefix, even though we know that length is (4+4). Right?

And is it really only the **first** element-bundle that is prefixed (as is stated in the description)?

**Comment by arobenko** [comment]
In the first two comments you are right. These are copy-paste errors, will fix them in the next "patch" update.

As for the last question. As the field is defined now, yes, the length is known to be 4+4 and the length of the first element seems to be redundant. But imagine the scenario when in the next version of the protocol, new field is added to the bundle. Having the element length information allows communication endpoint with old version of the protocol to communicate with newer one. It will read and understand 2 fields it knows about, but skip the irrelevant (or newly added) information thanks to the information of the element length, as the result the next element will be read at the correct location.

The element length prefix is there to facilitate protocol forward/backward compatibility (yes it is optional and you may drop its usage). However if it is used, by default every element is going to be prefixed by its length if <elemLengthPrefix> is defined. However, if there is a promise that every element will have fixed length (no fields like &lt;string&gt;, &lt;data&gt;, &lt;list&gt;) using **elemFixedLength="true"** property, then every element has the same length and it is redundant to prefix everyone with the same value. In this case only the first element is prefixed with length information relevant to everyone else. The definition of [F5](https://github.com/arobenko/cc.demo1.commsdsl/blob/dd4e1dc1fc150fc02c50972a7c7b744a4f424ce5/dsl/schema.xml#L236) field does set value of **elemFixedLength** to be **true**, as the result only the first element is prefixed with its length.

**Comment by arobenko** [comment]
Resolved in v0.6.1 bug fixing release
